import type {
  Product,
  PriceOptimization,
  InventoryForecast,
  CustomerSegment,
  RevenueMetrics,
  Promotion,
  ProductPerformanceRow,
  HeroStats,
} from "./types";

// ============================================================================
// 20 Products across categories
// ============================================================================
export const products: Product[] = [
  {
    id: "prod-001",
    name: "Quantum Wireless Earbuds Pro",
    category: "Electronics",
    sku: "ELEC-QWEP-001",
    currentPrice: 149.99,
    costPrice: 72.5,
    margin: 51.7,
    unitsSold: 2847,
    revenue: 427200,
    stockLevel: 340,
    reorderPoint: 200,
    status: "active",
  },
  {
    id: "prod-002",
    name: "UltraSlim Laptop Stand",
    category: "Electronics",
    sku: "ELEC-ULSS-002",
    currentPrice: 79.99,
    costPrice: 28.0,
    margin: 65.0,
    unitsSold: 1523,
    revenue: 121800,
    stockLevel: 89,
    reorderPoint: 150,
    status: "active",
  },
  {
    id: "prod-003",
    name: "Smart Desk Lamp with Qi Charging",
    category: "Electronics",
    sku: "ELEC-SDLQ-003",
    currentPrice: 89.99,
    costPrice: 41.0,
    margin: 54.4,
    unitsSold: 2100,
    revenue: 188900,
    stockLevel: 520,
    reorderPoint: 180,
    status: "active",
  },
  {
    id: "prod-004",
    name: "Premium Merino Wool Sweater",
    category: "Fashion",
    sku: "FASH-PMWS-004",
    currentPrice: 129.99,
    costPrice: 55.0,
    margin: 57.7,
    unitsSold: 987,
    revenue: 128300,
    stockLevel: 45,
    reorderPoint: 120,
    status: "active",
  },
  {
    id: "prod-005",
    name: "Athletic Performance Tee",
    category: "Fashion",
    sku: "FASH-APTE-005",
    currentPrice: 49.99,
    costPrice: 18.5,
    margin: 63.0,
    unitsSold: 3200,
    revenue: 159900,
    stockLevel: 780,
    reorderPoint: 300,
    status: "active",
  },
  {
    id: "prod-006",
    name: "Designer Sunglasses - Aviator",
    category: "Fashion",
    sku: "FASH-DSAV-006",
    currentPrice: 199.99,
    costPrice: 68.0,
    margin: 66.0,
    unitsSold: 654,
    revenue: 130700,
    stockLevel: 210,
    reorderPoint: 80,
    status: "active",
  },
  {
    id: "prod-007",
    name: "Organic Cotton Bed Sheet Set",
    category: "Home & Garden",
    sku: "HOME-OCBS-007",
    currentPrice: 89.99,
    costPrice: 34.0,
    margin: 62.2,
    unitsSold: 1876,
    revenue: 168800,
    stockLevel: 95,
    reorderPoint: 200,
    status: "active",
  },
  {
    id: "prod-008",
    name: "Smart Herb Garden Kit",
    category: "Home & Garden",
    sku: "HOME-SHGK-008",
    currentPrice: 69.99,
    costPrice: 29.5,
    margin: 57.9,
    unitsSold: 2341,
    revenue: 163800,
    stockLevel: 310,
    reorderPoint: 250,
    status: "active",
  },
  {
    id: "prod-009",
    name: "Cast Iron Dutch Oven 6qt",
    category: "Home & Garden",
    sku: "HOME-CIDO-009",
    currentPrice: 74.99,
    costPrice: 32.0,
    margin: 57.3,
    unitsSold: 1456,
    revenue: 109100,
    stockLevel: 175,
    reorderPoint: 160,
    status: "active",
  },
  {
    id: "prod-010",
    name: "Bamboo Cutting Board Set",
    category: "Home & Garden",
    sku: "HOME-BCBS-010",
    currentPrice: 39.99,
    costPrice: 14.0,
    margin: 65.0,
    unitsSold: 2900,
    revenue: 115900,
    stockLevel: 410,
    reorderPoint: 300,
    status: "active",
  },
  {
    id: "prod-011",
    name: "Carbon Fiber Running Shoes",
    category: "Sports",
    sku: "SPRT-CFRS-011",
    currentPrice: 179.99,
    costPrice: 76.0,
    margin: 57.8,
    unitsSold: 1234,
    revenue: 222100,
    stockLevel: 62,
    reorderPoint: 150,
    status: "active",
  },
  {
    id: "prod-012",
    name: "Adjustable Kettlebell 40lb",
    category: "Sports",
    sku: "SPRT-AKB4-012",
    currentPrice: 129.99,
    costPrice: 52.0,
    margin: 60.0,
    unitsSold: 876,
    revenue: 113800,
    stockLevel: 240,
    reorderPoint: 100,
    status: "active",
  },
  {
    id: "prod-013",
    name: "Yoga Mat Premium 6mm",
    category: "Sports",
    sku: "SPRT-YMP6-013",
    currentPrice: 59.99,
    costPrice: 21.0,
    margin: 65.0,
    unitsSold: 3400,
    revenue: 203900,
    stockLevel: 560,
    reorderPoint: 350,
    status: "active",
  },
  {
    id: "prod-014",
    name: "Vitamin C Brightening Serum",
    category: "Beauty",
    sku: "BEAU-VCBS-014",
    currentPrice: 44.99,
    costPrice: 12.0,
    margin: 73.3,
    unitsSold: 4500,
    revenue: 202400,
    stockLevel: 190,
    reorderPoint: 400,
    status: "active",
  },
  {
    id: "prod-015",
    name: "Retinol Night Cream",
    category: "Beauty",
    sku: "BEAU-RTNC-015",
    currentPrice: 54.99,
    costPrice: 16.0,
    margin: 70.9,
    unitsSold: 3200,
    revenue: 175900,
    stockLevel: 280,
    reorderPoint: 350,
    status: "active",
  },
  {
    id: "prod-016",
    name: "Hyaluronic Acid Moisturizer",
    category: "Beauty",
    sku: "BEAU-HAAM-016",
    currentPrice: 39.99,
    costPrice: 11.5,
    margin: 71.2,
    unitsSold: 5100,
    revenue: 203900,
    stockLevel: 125,
    reorderPoint: 500,
    status: "active",
  },
  {
    id: "prod-017",
    name: "Algorithm Design Handbook",
    category: "Books",
    sku: "BOOK-ADHB-017",
    currentPrice: 59.99,
    costPrice: 18.0,
    margin: 70.0,
    unitsSold: 2100,
    revenue: 125900,
    stockLevel: 680,
    reorderPoint: 200,
    status: "active",
  },
  {
    id: "prod-018",
    name: "Data Science for Business",
    category: "Books",
    sku: "BOOK-DSFB-018",
    currentPrice: 49.99,
    costPrice: 15.0,
    margin: 70.0,
    unitsSold: 1890,
    revenue: 94400,
    stockLevel: 440,
    reorderPoint: 180,
    status: "active",
  },
  {
    id: "prod-019",
    name: "AI Engineering Mastery",
    category: "Books",
    sku: "BOOK-AIEM-019",
    currentPrice: 69.99,
    costPrice: 22.0,
    margin: 68.6,
    unitsSold: 1650,
    revenue: 115400,
    stockLevel: 320,
    reorderPoint: 200,
    status: "active",
  },
  {
    id: "prod-020",
    name: "Cloud Architecture Patterns",
    category: "Books",
    sku: "BOOK-CARP-020",
    currentPrice: 54.99,
    costPrice: 17.5,
    margin: 68.2,
    unitsSold: 1450,
    revenue: 79700,
    stockLevel: 280,
    reorderPoint: 150,
    status: "active",
  },
];

// ============================================================================
// Price Optimization Recommendations
// ============================================================================
export const priceOptimizations: PriceOptimization[] = [
  {
    productId: "prod-001",
    currentPrice: 149.99,
    recommendedPrice: 164.99,
    confidence: 0.88,
    estimatedRevenueImpact: 9.8,
    estimatedMarginImpact: 14.2,
    reasoning:
      "Competitor average is $158. Low price elasticity (0.4) supports a 10% increase with minimal volume loss. High brand loyalty detected in this SKU.",
    elasticity: 0.4,
    competitorAvgPrice: 158.0,
  },
  {
    productId: "prod-004",
    currentPrice: 129.99,
    recommendedPrice: 119.99,
    confidence: 0.82,
    estimatedRevenueImpact: -3.5,
    estimatedMarginImpact: -6.1,
    reasoning:
      "Premium segment showing price fatigue. Reducing to $119.99 aligns with competitor pricing and should lift conversion by ~15% as per elasticity model.",
    elasticity: 1.8,
    competitorAvgPrice: 115.0,
  },
  {
    productId: "prod-006",
    currentPrice: 199.99,
    recommendedPrice: 219.99,
    confidence: 0.91,
    estimatedRevenueImpact: 8.2,
    estimatedMarginImpact: 15.3,
    reasoning:
      "Luxury positioning with very low elasticity (0.2). Brand cachet supports premium pricing. Competitors at $210-$230 range.",
    elasticity: 0.2,
    competitorAvgPrice: 215.0,
  },
  {
    productId: "prod-007",
    currentPrice: 89.99,
    recommendedPrice: 94.99,
    confidence: 0.79,
    estimatedRevenueImpact: 4.5,
    estimatedMarginImpact: 6.8,
    reasoning:
      "Organic premium justifies a modest uptick. Competitors average $92. Demand data shows low sensitivity in this segment.",
    elasticity: 0.6,
    competitorAvgPrice: 92.0,
  },
  {
    productId: "prod-011",
    currentPrice: 179.99,
    recommendedPrice: 189.99,
    confidence: 0.85,
    estimatedRevenueImpact: 5.2,
    estimatedMarginImpact: 7.9,
    reasoning:
      "Carbon fiber tech commands premium. Low stock + high demand supports price increase. Competitors at $180-$200.",
    elasticity: 0.5,
    competitorAvgPrice: 188.0,
  },
  {
    productId: "prod-014",
    currentPrice: 44.99,
    recommendedPrice: 49.99,
    confidence: 0.93,
    estimatedRevenueImpact: 10.1,
    estimatedMarginImpact: 13.8,
    reasoning:
      "High demand and strong reviews. Elasticity very low (0.25). Increasing to $49.99 still undercuts most competitors at $52-$58.",
    elasticity: 0.25,
    competitorAvgPrice: 54.0,
  },
  {
    productId: "prod-016",
    currentPrice: 39.99,
    recommendedPrice: 42.99,
    confidence: 0.87,
    estimatedRevenueImpact: 7.0,
    estimatedMarginImpact: 9.4,
    reasoning:
      "Volume leader with thin competitor pricing spread. Modest increase captures margin while protecting volume position.",
    elasticity: 0.45,
    competitorAvgPrice: 41.0,
  },
  {
    productId: "prod-020",
    currentPrice: 54.99,
    recommendedPrice: 49.99,
    confidence: 0.76,
    estimatedRevenueImpact: -2.1,
    estimatedMarginImpact: -3.4,
    reasoning:
      "High elasticity in tech books. $5 drop projected to lift units 18%, resulting in net revenue gain over 6 months.",
    elasticity: 1.9,
    competitorAvgPrice: 48.0,
  },
];

// ============================================================================
// Inventory Forecasts with Stockout Risks
// ============================================================================
export const inventoryForecasts: InventoryForecast[] = [
  {
    productId: "prod-002",
    currentStock: 89,
    dailyDemandAvg: 12.5,
    daysOfStockRemaining: 7,
    reorderPoint: 150,
    reorderQuantity: 300,
    stockoutRisk: "critical",
    leadTimeDays: 14,
    suggestedOrderDate: "2026-06-09",
    seasonalFactor: 1.2,
  },
  {
    productId: "prod-004",
    currentStock: 45,
    dailyDemandAvg: 8.2,
    daysOfStockRemaining: 5,
    reorderPoint: 120,
    reorderQuantity: 250,
    stockoutRisk: "critical",
    leadTimeDays: 10,
    suggestedOrderDate: "2026-06-09",
    seasonalFactor: 1.0,
  },
  {
    productId: "prod-007",
    currentStock: 95,
    dailyDemandAvg: 15.6,
    daysOfStockRemaining: 6,
    reorderPoint: 200,
    reorderQuantity: 400,
    stockoutRisk: "high",
    leadTimeDays: 12,
    suggestedOrderDate: "2026-06-10",
    seasonalFactor: 1.3,
  },
  {
    productId: "prod-011",
    currentStock: 62,
    dailyDemandAvg: 10.3,
    daysOfStockRemaining: 6,
    reorderPoint: 150,
    reorderQuantity: 300,
    stockoutRisk: "high",
    leadTimeDays: 14,
    suggestedOrderDate: "2026-06-09",
    seasonalFactor: 1.1,
  },
  {
    productId: "prod-014",
    currentStock: 190,
    dailyDemandAvg: 37.5,
    daysOfStockRemaining: 5,
    reorderPoint: 400,
    reorderQuantity: 600,
    stockoutRisk: "critical",
    leadTimeDays: 8,
    suggestedOrderDate: "2026-06-09",
    seasonalFactor: 1.4,
  },
  {
    productId: "prod-016",
    currentStock: 125,
    dailyDemandAvg: 42.5,
    daysOfStockRemaining: 3,
    reorderPoint: 500,
    reorderQuantity: 700,
    stockoutRisk: "critical",
    leadTimeDays: 7,
    suggestedOrderDate: "2026-06-09",
    seasonalFactor: 1.5,
  },
  {
    productId: "prod-001",
    currentStock: 340,
    dailyDemandAvg: 23.7,
    daysOfStockRemaining: 14,
    reorderPoint: 200,
    reorderQuantity: 350,
    stockoutRisk: "low",
    leadTimeDays: 14,
    suggestedOrderDate: "2026-06-18",
    seasonalFactor: 1.0,
  },
  {
    productId: "prod-003",
    currentStock: 520,
    dailyDemandAvg: 17.5,
    daysOfStockRemaining: 30,
    reorderPoint: 180,
    reorderQuantity: 250,
    stockoutRisk: "low",
    leadTimeDays: 10,
    suggestedOrderDate: "2026-06-30",
    seasonalFactor: 0.9,
  },
  {
    productId: "prod-005",
    currentStock: 780,
    dailyDemandAvg: 26.7,
    daysOfStockRemaining: 29,
    reorderPoint: 300,
    reorderQuantity: 400,
    stockoutRisk: "low",
    leadTimeDays: 12,
    suggestedOrderDate: "2026-06-28",
    seasonalFactor: 1.0,
  },
  {
    productId: "prod-013",
    currentStock: 560,
    dailyDemandAvg: 28.3,
    daysOfStockRemaining: 20,
    reorderPoint: 350,
    reorderQuantity: 450,
    stockoutRisk: "medium",
    leadTimeDays: 10,
    suggestedOrderDate: "2026-06-18",
    seasonalFactor: 1.1,
  },
];

// ============================================================================
// 6 Customer Segments
// ============================================================================
export const customerSegments: CustomerSegment[] = [
  {
    id: "seg-vip",
    name: "VIP High-Value",
    description:
      "Top 5% of customers by lifetime value. Frequent purchasers with high AOV and strong brand loyalty.",
    customerCount: 1240,
    percentageOfBase: 5.0,
    avgOrderValue: 187.5,
    arpu: 2240.0,
    lifetimeValue: 8960.0,
    churnRisk: 0.03,
    growthRate: 12.4,
    color: "#5b5bd6",
  },
  {
    id: "seg-loyal",
    name: "Loyal Regulars",
    description:
      "Consistent monthly purchasers with above-average retention. Core revenue drivers.",
    customerCount: 4500,
    percentageOfBase: 18.1,
    avgOrderValue: 98.4,
    arpu: 1180.0,
    lifetimeValue: 3540.0,
    churnRisk: 0.08,
    growthRate: 5.2,
    color: "#22c55e",
  },
  {
    id: "seg-at-risk",
    name: "At-Risk Decliners",
    description:
      "Previously loyal customers showing declining purchase frequency. High churn probability.",
    customerCount: 3200,
    percentageOfBase: 12.9,
    avgOrderValue: 72.3,
    arpu: 580.0,
    lifetimeValue: 1740.0,
    churnRisk: 0.45,
    growthRate: -8.1,
    color: "#f59e0b",
  },
  {
    id: "seg-new",
    name: "New Acquisitions",
    description:
      "Customers acquired in the last 90 days. High growth potential but unproven retention.",
    customerCount: 6800,
    percentageOfBase: 27.4,
    avgOrderValue: 65.0,
    arpu: 195.0,
    lifetimeValue: 780.0,
    churnRisk: 0.35,
    growthRate: 28.7,
    color: "#3b82f6",
  },
  {
    id: "seg-dormant",
    name: "Dormant Accounts",
    description:
      "No purchase in 6+ months. Require re-engagement campaigns to reactivate.",
    customerCount: 5600,
    percentageOfBase: 22.6,
    avgOrderValue: 45.2,
    arpu: 90.0,
    lifetimeValue: 360.0,
    churnRisk: 0.75,
    growthRate: -15.3,
    color: "#ef4444",
  },
  {
    id: "seg-bargain",
    name: "Bargain Hunters",
    description:
      "Price-sensitive segment that only purchases during promotions. Low margin but high volume.",
    customerCount: 3500,
    percentageOfBase: 14.1,
    avgOrderValue: 38.9,
    arpu: 234.0,
    lifetimeValue: 702.0,
    churnRisk: 0.22,
    growthRate: 3.8,
    color: "#8b5cf6",
  },
];

// ============================================================================
// Revenue Metrics
// ============================================================================
export const revenueMetrics: RevenueMetrics = {
  totalRevenue: 3240000,
  revenueGrowth: 18.4,
  grossMargin: 62.3,
  netProfit: 845000,
  averageOrderValue: 87.5,
  conversionRate: 4.8,
  customerAcquisitionCost: 42.0,
  customerLifetimeValue: 1840.0,
  activeCustomers: 24800,
  churnRate: 3.2,
  periodStart: "2026-01-01",
  periodEnd: "2026-06-08",
};

// ============================================================================
// 5 Active Promotions
// ============================================================================
export const promotions: Promotion[] = [
  {
    id: "promo-summer-sale",
    name: "Summer Launch Sale",
    type: "percentage",
    discountValue: 20,
    applicableProducts: ["prod-001", "prod-003", "prod-006", "prod-011"],
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    budget: 50000,
    spentSoFar: 18700,
    revenueGenerated: 142000,
    ordersInfluenced: 820,
    status: "active",
    roi: 659.4,
  },
  {
    id: "promo-free-ship",
    name: "Free Shipping Weekend",
    type: "free_shipping",
    discountValue: 9.99,
    applicableProducts: ["all"],
    startDate: "2026-06-05",
    endDate: "2026-06-08",
    budget: 15000,
    spentSoFar: 8900,
    revenueGenerated: 78500,
    ordersInfluenced: 1200,
    status: "active",
    roi: 782.0,
  },
  {
    id: "promo-bundle-deal",
    name: "Home Essentials Bundle",
    type: "bundle",
    discountValue: 15,
    applicableProducts: ["prod-007", "prod-008", "prod-009", "prod-010"],
    startDate: "2026-06-01",
    endDate: "2026-07-15",
    budget: 25000,
    spentSoFar: 6200,
    revenueGenerated: 48000,
    ordersInfluenced: 340,
    status: "active",
    roi: 674.2,
  },
  {
    id: "promo-beauty-bogo",
    name: "Beauty BOGO 50% Off",
    type: "bogo",
    discountValue: 50,
    applicableProducts: ["prod-014", "prod-015", "prod-016"],
    startDate: "2026-06-03",
    endDate: "2026-06-20",
    budget: 30000,
    spentSoFar: 14200,
    revenueGenerated: 112000,
    ordersInfluenced: 1560,
    status: "active",
    roi: 688.7,
  },
  {
    id: "promo-loyalty-bonus",
    name: "Loyalty Member Bonus 10%",
    type: "percentage",
    discountValue: 10,
    applicableProducts: ["all"],
    startDate: "2026-05-15",
    endDate: "2026-08-15",
    budget: 80000,
    spentSoFar: 31000,
    revenueGenerated: 245000,
    ordersInfluenced: 2100,
    status: "active",
    roi: 690.3,
  },
];

// ============================================================================
// Aggregated Views
// ============================================================================
export function getProductPerformanceRows(): ProductPerformanceRow[] {
  return products.map((product) => ({
    product,
    priceOptimization: priceOptimizations.find(
      (po) => po.productId === product.id
    ),
    inventory: inventoryForecasts.find((inv) => inv.productId === product.id),
  }));
}

export function getHeroStats(): HeroStats {
  const criticalAndHigh = inventoryForecasts.filter(
    (f) => f.stockoutRisk === "critical" || f.stockoutRisk === "high"
  );
  return {
    totalRevenue: revenueMetrics.totalRevenue,
    grossMargin: revenueMetrics.grossMargin,
    stockoutRiskCount: criticalAndHigh.length,
    activeSegments: customerSegments.filter((s) => s.churnRisk < 0.5).length,
    activePromotions: promotions.filter((p) => p.status === "active").length,
    revenueGrowth: revenueMetrics.revenueGrowth,
  };
}

export function getStockoutAlerts(): InventoryForecast[] {
  return inventoryForecasts
    .filter(
      (f) =>
        f.stockoutRisk === "critical" || f.stockoutRisk === "high"
    )
    .sort((a, b) => a.daysOfStockRemaining - b.daysOfStockRemaining);
}
